name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
  
    - name: Restore
      run: dotnet restore ./test-sol.sln
  
    - name: Build
      run: dotnet build ./test-sol.sln --configuration Release
  
    - name: Publish
      run: dotnet publish ./test-sol.sln --configuration Release --no-build --output './publish'

    - name: Deployment
      uses: azure/webapps-deploy@v2
      with:
        app-name: my-todo-net-app
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: './publish'
